services:
  - type: web
    name: velli-prospect
    runtime: python
    plan: free
    region: ohio
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: FLET_FORCE_WEB_SERVER
        value: "true"
      - key: FLET_SERVER_IP
        value: "0.0.0.0"
