services:
  - type: web
    name: velli-prospect
    env: docker
    plan: free
    region: ohio
    branch: main
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: FLET_FORCE_WEB_SERVER
        value: "true"
